### ISSUE TITLE
Interface redesign

### ISSUE THREAD

**Issue by nebocoder** [error401de/stpauli-tracker#17]
I found this project while looking to contribute for Hacktoberfest and I really liked the idea, especially because I've heard of the club before.

I was wondering are there any interface redesign plans? I quickly made something just to explore how a new interface might look like. I will also gladly implement the new design!

Here is an image of my design attempt (not very good), please feel free to suggest any changes that come to mind. Gray boxes represent text placeholders.

![st-pauli](https://user-images.githubusercontent.com/91620216/193426729-9e620213-04c8-401f-bd0c-d2dabe05f1d6.png)

**Comment by error401de** [comment]
Hi @nebocoder 
thank you so much for your interest!

I am myself currently focusing on the functionality, so it would be much appreciated if you would enhance the interface.

I absolutely do love the header!
But I would like a white (or at least brighter) background more, it feels more "light".
Would you have an idea how to combine the header with a brighter version of the background color?

And: Please make sure that everything is mobile optimised as it is now: On a phone all boxes should have the same width :)

**Comment by nebocoder** [comment]
I am glad you like the design direction! 😊

I think white background works just as well with the header, no need for any changes. I gave boxes this off white color, in my opinion it looks better if boxes also remain light with dark text.

One more thing about text is that in the design I use "Inter" font. Would you prefer if the font stack remained as it is or is importing a Google font okay?

![st-pauli2](https://user-images.githubusercontent.com/91620216/193428374-c791309a-9e16-4d04-874e-ca362138cf5f.png)

**Comment by error401de** [comment]
Looks awesome!
Feel free to use Google Fonts, but please make sure to include them into the app itself (so please don't include them directly from Google's servers)
