### ISSUE TITLE
Issue with mobile view on new UI

### ISSUE THREAD

**Issue by error401de** [error401de/stpauli-tracker#20]
Follow-up of #19 

Content in mobile view is not fully centered, also the UI might look better if there is a small padding around the boxes (at least it's worth a try, I guess)

<img width="293" alt="image" src="https://user-images.githubusercontent.com/34032466/193453071-23c2e466-b2fa-4444-a5b0-673afae5a8f0.png">

**Comment by nebocoder** [comment]
This also gets addressed in #23 🙂

**Comment by error401de** [comment]
Looking awesome, thanks!
