### ISSUE TITLE
Fit more content on web view

### ISSUE THREAD

**Issue by error401de** [error401de/stpauli-tracker#21]
Currently it's not possible to show the full content on 13" display. Maybe it's possible to optimise this. If not, it is like it is :)

**Comment by nebocoder** [comment]
I played around a little and I think fitting more content is possible but there will still be some vertical scrolling on smaller screens if we wanna keep some white space.

**Comment by error401de** [comment]
I guess if there is still scrolling required (I also think we should keep a little white space), it's more a general question what looks better. Up to you, you have the better eye for this :)

**Comment by error401de** [comment]
Looking awesome, thanks!
