### ISSUE TITLE
Highlight end scores better

### ISSUE THREAD

**Issue by error401de** [error401de/stpauli-tracker#24]
Currently the end scores in "Letzte Spiele" box is shown just as numbers. It would be nice if the scores are highlighted somehow, to quickly see if it's a win, loss or even.
Highlighting it with a background color, similar to the "St. Pauli" highlighting in the first box, might work. More ideas are very welcome.
//EDIT: To clarify further: The background color of the end score should depend on the result. If the team one, it might be green, draw might be yellow and loss might be red.

**Comment by palaksv** [comment]
Please assign this to me

**Comment by error401de** [comment]
There you go, have fun :)
